- platform: template
  sensors:

    front_door:
      device_class: opening
      value_template: >
        {%- if is_state('sensor.front_door',"22") -%}
        on
        {%- else -%}
        off
        {%- endif -%}

    back_door:
      device_class: opening
      value_template: >
        {%- if is_state('sensor.back_door',"22") -%}
        on
        {%- else -%}
        off
        {%- endif -%}
