

- alias: Movement in dining room detected
  trigger:
    - platform: state
      entity_id: binary_sensor.linear_wapirz1_motion_1
      to: 'on'
  action:
    #- service: notify.slack
    #  data_template:
    #    message: 'movement in dining room, lights at {{ states.light.dining_room.attributes.brightness | int }}'
    - service: timer.cancel
      entity_id: timer.motion_dining_room_dim
    - service: timer.cancel
      entity_id: timer.motion_dining_room_off

- alias: No movement in dining room detected
  trigger:
    - platform: state
      entity_id: binary_sensor.linear_wapirz1_motion_1
      to: 'off'
  action:
    #- service: notify.slack
    #  data_template:
    #    message: 'no motion in dining room, starting timers'
    - service: input_number.set_value
      data_template:
        entity_id: input_number.dining_room
        value: '{{ states.light.dininig_room.attributes.brightness | int }}'
    - service: timer.start
      entity_id: timer.motion_dining_room_dim
    - service: timer.start
      entity_id: timer.motion_dining_room_off
      #data:
      #  duration: '00:05:00'

- alias: Dim dining room lights if no movement
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.motion_dining_room_dim
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.linear_wapirz1_motion_1
        state: 'off'
      - condition: state
        entity_id: light.dining_room
        state: 'on'
  action:
    #- service: notify.slack
    #  data_template:
    #    message: "Dimming dining room light to {{ ( states.light.dining_room.attributes.brightness / 2 ) | int }}"
    - service: light.turn_on
      entity_id: light.dining_room
      data_template:
        transition: 8
        brightness: '{{ ( states.light.dining_room.attributes.brightness / 2 ) | int }}'

- alias: Turn dining room lights back up if movment
  trigger:
    - platform: state
      entity_id: binary_sensor.linear_wapirz1_motion_1
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('timer.motion_dining_room_off', 'active' ) }}"
      - condition: template
        value_template: "{{ is_state('timer.motion_dining_room_dim', 'idle' ) }}"
      - condition: state
        entity_id: light.dining_room
        state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.motion_dining_room_off
    - service: light.turn_on
      entity_id: light.dining_room
      data_template:
        transition: 1
        brightness: "{{ states('input_number.dining_room') | int  }}"
    #- service: notify.slack
    #  data_template:
    #    message: 'turning dining room lights back to previous level'


- alias: Turn dining room lights off if no movement
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.motion_dining_room_off
  condition:
    condition: 'and'
    conditions:
      - condition: state
        entity_id: binary_sensor.linear_wapirz1_motion_1
        state: 'off'
      - condition: state
        entity_id: light.dining_room
        state: 'on'
      - condition: template
        value_template: "{{ ( states.light.dining_room.attributes.brightness | int ) <= ( states('input_number.dining_room') | int ) }}"
  action:
    #- service: notify.slack
    #  data_template:
    #    message: "Turning off dining room light (current state {{ states.light.dining_room }})"
    - service: light.turn_off
      entity_id: light.dining_room
      data_template:
        transition: 8
