- alias: Person as just arrived home
  trigger:
    - platform: state
      entity_id: device_tracker.yeespixel
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.pspixel
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.yeespixel' %}
            input_select.yee_location_dropdown
          {% else %}
            input_select.pi_location_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'device_tracker.yeespixel' %}
            {% if states.input_select.yee_location_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.yee_location_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}

- alias: Person at home
  trigger:
    - platform: state
      entity_id: input_select.yee_location_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.pi_location_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.yee_location_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.pi_location_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.yee_location_dropdown' %}
            input_select.yee_location_dropdown
          {% else %}
            input_select.pi_location_dropdown
          {% endif %}
        option: Home
 
- alias: Person has just left
  trigger:
    - platform: state
      entity_id: device_tracker.yeespixel
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.psiphone
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.yeespixel' %}
            input_select.yee_location_dropdown
          {% else %}
            input_select.pi_location_dropdown
          {% endif %}
        option: Just Left
 
- alias: Person gone away
  trigger:
    - platform: state
      entity_id: input_select.yee_location_dropdown
      to: 'Just Left'
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.pi_location_dropdown
      to: 'Just Left'
      for:
        minutes: 5
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.yee_location_dropdown' %}
            input_select.yee_location_dropdown
          {% else %}
            input_select.pi_location_dropdown
          {% endif %}
        option: Away
 
- alias: Person is extended away
  trigger:
    - platform: state
      entity_id: input_select.yee_location_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.pi_location_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.yee_location_dropdown' %}
            input_select.yee_location_dropdown
          {% else %}
            input_select.pi_location_dropdown
          {% endif %}
        option: Extended Away
