- alias: Set Nighttime
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:45:00"
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 5.0
  action:
    - service: input_boolean.turn_on
      entity_id:  input_boolean.is_dark
    - service: notify.slack
      data_template:
        message: "Setting it is dark"

- alias: Set Daytime
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:30:00"
  action:
    - service: input_boolean.turn_off
      entity_id:  input_boolean.is_dark
    - service: notify.slack
      data_template:
        message: "Setting it is day"


- alias: Turn on hallway lights at night
  trigger:
    - platform: state
      entity_id: input_boolean.is_dark
      to: 'on' 
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ is_state('input_boolean.at_home','on') }}"
  action:
    - service: notify.slack
      data_template:
        message: "Turning on hallway light"
    #- service: light.turn_on
    #  entity_id: light.hallway
    - service: scene.turn_on
      entity_id: scene.hallway_nightlight
    - service: notify.slack
      data_template:
        message: "Turned on hallway light"

- alias: Turn off hallway lights in the morning
  trigger:
    - platform: state
      entity_id: input_boolean.is_dark
      to: 'off'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ is_state( 'input_boolean.at_home', 'on' ) }}"
  action:
    - service: notify.slack
      data_template:
        message: "Turning off hallway light"
    - service: light.turn_off
      entity_id: light.hallway
    - service: notify.slack
      data_template:
        message: "Turned off hallway light"
