arlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

sensor:
  - platform: arlo
    #monitored_conditions:
    #  - captured_today
    #  - last_capture
    #  - total_cameras
    #  - battery_level
    #  - signal_strength

alarm_control_panel:
  - platform: arlo

